"""End-to-end verification against the assignment's success criteria."""

from __future__ import annotations

from pathlib import Path

STYLE_ID = "test_style"

INPUTS = [
    "회사에서 아무도 안 알려주는 엑셀 단축키 정리",
    "자취 3년차가 후회하는 가전 구매 순서",
    "러닝 시작 첫 달에 무릎이 아픈 진짜 이유",
]


def test_health(client):
    body = client.get("/health").json()
    assert body["status"] == "ok"
    assert body["video_provider"] == "mock"


def test_extract_style(client, reference_video: Path):
    with reference_video.open("rb") as fh:
        resp = client.post(
            "/styles/extract",
            data={"style_id": STYLE_ID, "notes": "test fixture"},
            files={"files": ("reference.mp4", fh, "video/mp4")},
        )
    assert resp.status_code == 201, resp.text
    style = resp.json()

    # The fixture has six ~1.2s segments; extraction must recover that pacing.
    assert 0.6 <= style["pacing"]["avg_shot_sec"] <= 2.0
    assert style["pacing"]["shot_count"] >= 3
    assert style["style_id"] == STYLE_ID
    assert STYLE_ID in client.get("/styles").json()


def test_hook_is_non_deterministic(client):
    """Same input, repeated generation -> the hook must be able to differ.

    This is the requirement that the hook is generated by the system and is not
    frozen. Asserting >1 distinct text is the weakest claim that still falsifies
    a hardcoded hook.
    """
    resp = client.post(
        "/hooks/preview",
        json={"style_id": STYLE_ID, "text": INPUTS[0], "n": 8},
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()

    assert body["distinct_texts"] > 1
    assert body["distinct_archetypes"] > 1

    first = body["results"][0]
    assert first["entropy_source"].startswith("secrets.SystemRandom")
    assert first["selection_method"].startswith("top_k_softmax")
    assert len(first["candidates"]) >= 2
    assert first["selected"]["text"] in [c["text"] for c in first["candidates"]]


def test_run_produces_video(client):
    resp = client.post("/runs", data={"style_id": STYLE_ID, "text": INPUTS[0]})
    assert resp.status_code == 202, resp.text
    run_id = resp.json()["run_id"]

    # TestClient drains BackgroundTasks before returning, so the run is finished.
    run = client.get(f"/runs/{run_id}").json()
    assert run["status"] == "done", run.get("error")

    final = Path(run["artifacts"]["final_video"])
    assert final.exists() and final.stat().st_size > 0
    assert run["hook_text"]
    assert run["hook_archetype"]

    assert client.get(f"/runs/{run_id}/video").status_code == 200
    storyboard = client.get(f"/runs/{run_id}/artifacts/storyboard.json").json()
    assert any(s["role"] == "hook" for s in storyboard["shots"])
    assert storyboard["shots"][0]["caption"] == run["hook_text"]

    # Regression: the outline used to pass the model's raw durations straight
    # through, so a 7s reference produced a 19s video.
    style = client.get(f"/styles/{STYLE_ID}").json()
    planned = sum(s["duration_sec"] for s in storyboard["shots"])
    budget = max(style["total_duration"], style["hook_style"]["window_sec"] + 6.0)
    assert planned <= budget + 1.0, f"{planned}s exceeds style budget {budget}s"


def test_hook_candidates_are_distinct(client):
    """Duplicate candidates would make the softmax draw a no-op."""
    body = client.post(
        "/hooks/preview", json={"style_id": STYLE_ID, "text": INPUTS[1], "n": 3}
    ).json()
    for result in body["results"]:
        texts = [c["text"] for c in result["candidates"]]
        assert len(texts) == len(set(texts))


def test_batch_three_inputs_diverge(client):
    """The deliverable: three different inputs through one unchanged system."""
    resp = client.post("/runs/batch", json={"style_id": STYLE_ID, "inputs": INPUTS})
    assert resp.status_code == 202, resp.text
    run_ids = [r["run_id"] for r in resp.json()]
    assert len(run_ids) == 3

    runs = [client.get(f"/runs/{rid}").json() for rid in run_ids]
    for run in runs:
        assert run["status"] == "done", run.get("error")
        assert Path(run["artifacts"]["final_video"]).exists()

    # Different inputs must yield different hooks...
    assert len({r["hook_text"] for r in runs}) == 3
    # ...while every one still conforms to the same style schema.
    assert all(r["qc_score"] is not None for r in runs)


def test_unknown_style_is_404(client):
    assert client.get("/styles/nope").status_code == 404
    assert client.post("/runs", data={"style_id": "nope", "text": "x"}).status_code == 404


def test_run_requires_some_input(client):
    assert client.post("/runs", data={"style_id": STYLE_ID}).status_code == 400
